(define (simpson f a b n)
  (define h (/ (- b a) n))
  (define (y k) (f (+ a (* k h))))
  (define (simpson-term k)
    (cond ((= k 0) (y 0))
          ((= k n) (y n))
          ((even? k) (* 2 (y k)))
          (else (* 4 (y k)))))
  (* (/ h 3) (sum simpson-term 0 inc n)))
(integral cube 0 1 0.01)
(simpson cube 0 1.0 100)
(integral cube 0 1 0.001)
(simpson cube 0 1.0 1000)
